import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import axios from 'axios';
import {
  BNPLCheckoutRequest,
  BNPLCheckoutResponse,
  BNPLRefundRequest,
  BNPLRefundResponse,
  TabbyCheckoutSession,
} from '../../interfaces/bnpl.interface';

/**
 * Tabby Payment Service
 * Handles Tabby Buy Now Pay Later integration
 * 
 * Tabby offers 4 interest-free installments
 */
@Injectable()
export class TabbyService {
  private readonly logger = new Logger(TabbyService.name);
  private readonly apiUrl: string;
  private readonly publicKey: string;
  private readonly secretKey: string;
  private readonly merchantCode: string;

  constructor() {
    // Sandbox: https://api.tabby.ai/api/v2
    // Production: https://api.tabby.ai/api/v2
    this.apiUrl = process.env.TABBY_API_URL || 'https://api.tabby.ai/api/v2';
    this.publicKey = process.env.TABBY_PUBLIC_KEY || '';
    this.secretKey = process.env.TABBY_SECRET_KEY || '';
    this.merchantCode = process.env.TABBY_MERCHANT_CODE || '';
  }

  /**
   * Check if amount is eligible for Tabby
   * Tabby typically requires minimum 100 SAR
   */
  isEligible(amount: number): boolean {
    const minAmount = parseFloat(process.env.TABBY_MIN_AMOUNT || '100');
    const maxAmount = parseFloat(process.env.TABBY_MAX_AMOUNT || '10000');
    
    return amount >= minAmount && amount <= maxAmount;
  }

  /**
   * Create Tabby checkout session
   */
  async createCheckout(request: BNPLCheckoutRequest): Promise<BNPLCheckoutResponse> {
    try {
      const session: TabbyCheckoutSession = {
        id: '', // Will be generated by Tabby
        payment: {
          amount: request.amount.toFixed(2),
          currency: request.currency,
          description: request.description,
        },
        buyer: {
          email: request.customer.email,
          phone: request.customer.phone,
          name: `${request.customer.firstName} ${request.customer.lastName}`,
        },
        order: {
          reference_id: request.registrationId,
          items: [
            {
              title: request.description,
              quantity: 1,
              unit_price: request.amount.toFixed(2),
              category: 'Education',
            },
          ],
        },
        merchant_urls: {
          success: request.successUrl,
          cancel: request.cancelUrl,
          failure: request.failureUrl,
        },
      };

      const response = await axios.post(
        `${this.apiUrl}/checkout`,
        session,
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
            'Content-Type': 'application/json',
          },
        },
      );

      this.logger.log(`Tabby checkout session created: ${response.data.id}`);

      return {
        success: true,
        checkoutUrl: response.data.configuration.available_products.installments[0].web_url,
        sessionId: response.data.id,
      };
    } catch (error) {
      this.logger.error('Tabby checkout creation failed:', error.response?.data || error.message);
      return {
        success: false,
        error: error.response?.data?.message || 'فشل إنشاء جلسة الدفع مع Tabby',
      };
    }
  }

  /**
   * Retrieve payment status from Tabby
   */
  async getPaymentStatus(sessionId: string): Promise<any> {
    try {
      const response = await axios.get(
        `${this.apiUrl}/checkout/${sessionId}`,
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
          },
        },
      );

      return response.data;
    } catch (error) {
      this.logger.error('Failed to get Tabby payment status:', error);
      throw new BadRequestException('فشل الحصول على حالة الدفع');
    }
  }

  /**
   * Capture payment (confirm the order)
   */
  async capturePayment(sessionId: string, amount: number): Promise<any> {
    try {
      const response = await axios.post(
        `${this.apiUrl}/payments/${sessionId}/captures`,
        {
          amount: amount.toFixed(2),
        },
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
            'Content-Type': 'application/json',
          },
        },
      );

      this.logger.log(`Tabby payment captured: ${sessionId}`);
      return response.data;
    } catch (error) {
      this.logger.error('Tabby payment capture failed:', error);
      throw new BadRequestException('فشل تأكيد الدفع');
    }
  }

  /**
   * Refund a Tabby payment
   */
  async refundPayment(request: BNPLRefundRequest): Promise<BNPLRefundResponse> {
    try {
      const response = await axios.post(
        `${this.apiUrl}/payments/${request.sessionId}/refunds`,
        {
          amount: request.amount.toFixed(2),
          reason: request.reason || 'Customer request',
        },
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
            'Content-Type': 'application/json',
          },
        },
      );

      this.logger.log(`Tabby refund created: ${response.data.id}`);

      return {
        success: true,
        refundId: response.data.id,
      };
    } catch (error) {
      this.logger.error('Tabby refund failed:', error);
      return {
        success: false,
        error: error.response?.data?.message || 'فشل إرجاع المبلغ',
      };
    }
  }

  /**
   * Verify webhook signature
   */
  verifyWebhookSignature(payload: any, signature: string): boolean {
    // Implement Tabby webhook signature verification
    // This is a placeholder - implement according to Tabby's documentation
    return true;
  }
}
