import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import axios from 'axios';
import {
  BNPLCheckoutRequest,
  BNPLCheckoutResponse,
  BNPLRefundRequest,
  BNPLRefundResponse,
  TabbyCheckoutSession,
} from '../../interfaces/bnpl.interface';

/**
 * Tabby Payment Service
 * Handles Tabby Buy Now Pay Later integration
 * 
 * Tabby offers 4 interest-free installments
 */
@Injectable()
export class TabbyService {
  private readonly logger = new Logger(TabbyService.name);
  private readonly apiUrl: string;
  private readonly publicKey: string;
  private readonly secretKey: string;
  private readonly merchantCode: string;

  constructor() {
    // Sandbox: https://api.tabby.ai/api/v2
    // Production: https://api.tabby.ai/api/v2
    this.apiUrl = process.env.TABBY_API_URL || 'https://api.tabby.ai/api/v2';
    this.publicKey = process.env.TABBY_PUBLIC_KEY || '';
    this.secretKey = process.env.TABBY_SECRET_KEY || '';
    this.merchantCode = process.env.TABBY_MERCHANT_CODE || '';
  }

  /**
   * Check if amount is eligible for Tabby
   * Tabby typically requires minimum 100 SAR
   */
  isEligible(amount: number): boolean {
    const minAmount = parseFloat(process.env.TABBY_MIN_AMOUNT || '100');
    const maxAmount = parseFloat(process.env.TABBY_MAX_AMOUNT || '10000');
    
    return amount >= minAmount && amount <= maxAmount;
  }

  /**
   * Get available installment options from Tabby for a given amount
   * This calls Tabby's API to get real-time available products
   */
  async getInstallmentOptions(amount: number, currency: string = 'SAR'): Promise<any[]> {
    try {
      // Create a temporary session to get available products
      const response = await axios.post(
        `${this.apiUrl}/checkout`,
        {
          payment: {
            amount: amount.toFixed(2),
            currency,
          },
          buyer: {
            email: 'temp@example.com',
            phone: '+966500000000',
            name: 'Temp User',
          },
          order: {
            reference_id: 'temp-' + Date.now(),
            items: [{
              title: 'Temp Item',
              quantity: 1,
              unit_price: amount.toFixed(2),
              category: 'Education',
            }],
          },
          merchant_urls: {
            success: process.env.FRONTEND_URL || 'http://localhost:3000',
            cancel: process.env.FRONTEND_URL || 'http://localhost:3000',
            failure: process.env.FRONTEND_URL || 'http://localhost:3000',
          },
        },
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
            'Content-Type': 'application/json',
          },
        },
      );

      // Extract available installment products
      const availableProducts = response.data.configuration?.available_products?.installments || [];
      
      return availableProducts.map((product: any) => ({
        installments: product.installments_count || 4,
        minLimit: parseFloat(product.min_limit?.amount || '0'),
        maxLimit: parseFloat(product.max_limit?.amount || '0'),
        installmentAmount: amount / (product.installments_count || 4),
      }));
    } catch (error) {
      this.logger.error('Failed to get Tabby installment options:', error.response?.data || error.message);
      // Fallback to default
      return [{
        installments: 4,
        minLimit: 100,
        maxLimit: 10000,
        installmentAmount: amount / 4,
      }];
    }
  }

  /**
   * Create Tabby checkout session
   * PRODUCTION-READY: Includes language support and proper error handling
   */
  async createCheckout(request: BNPLCheckoutRequest, language: string = 'ar'): Promise<BNPLCheckoutResponse> {
    try {
      const session: TabbyCheckoutSession = {
        id: '', // Will be generated by Tabby
        payment: {
          amount: request.amount.toFixed(2),
          currency: request.currency,
          description: request.description,
        },
        lang: language, // CRITICAL: Language parameter for Arabic/English
        buyer: {
          email: request.customer.email,
          phone: request.customer.phone,
          name: `${request.customer.firstName} ${request.customer.lastName}`,
        },
        order: {
          reference_id: request.registrationId,
          items: [
            {
              title: request.description,
              quantity: 1,
              unit_price: request.amount.toFixed(2),
              category: 'Education',
            },
          ],
        },
        merchant_urls: {
          success: request.successUrl,
          cancel: request.cancelUrl,
          failure: request.failureUrl,
        },
      };

      const response = await axios.post(
        `${this.apiUrl}/checkout`,
        session,
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
            'Content-Type': 'application/json',
          },
        },
      );

      const sessionData = response.data;
      const sessionStatus = sessionData.status;

      this.logger.log(`Tabby checkout session created: ${sessionData.id}, status: ${sessionStatus}`);

      // Check if customer is eligible (pre-scoring)
      if (sessionStatus === 'rejected') {
        const rejectionReason = sessionData.configuration?.products?.installments?.rejection_reason || 'not_available';
        this.logger.warn(`Tabby checkout rejected: ${rejectionReason}`);
        return {
          success: false,
          error: this.getRejectionMessage(rejectionReason),
        };
      }

      // Extract checkout URL
      const installmentProducts = sessionData.configuration?.available_products?.installments || [];
      if (installmentProducts.length === 0) {
        return {
          success: false,
          error: 'لا توجد خيارات تقسيط متاحة من Tabby',
        };
      }

      return {
        success: true,
        checkoutUrl: installmentProducts[0].web_url,
        sessionId: sessionData.id,
        paymentId: sessionData.payment?.id, // Save payment ID for verification
      };
    } catch (error) {
      this.logger.error('Tabby checkout creation failed:', error.response?.data || error.message);
      return {
        success: false,
        error: error.response?.data?.message || 'فشل إنشاء جلسة الدفع مع Tabby',
      };
    }
  }

  /**
   * Retrieve payment status from Tabby
   * PRODUCTION-READY: Proper error handling and logging
   */
  async getPaymentStatus(paymentId: string): Promise<any> {
    try {
      // Use payments endpoint, not checkout endpoint
      const response = await axios.get(
        `${this.apiUrl}/payments/${paymentId}`,
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
          },
        },
      );

      this.logger.log(`Tabby payment status: ${paymentId} - ${response.data.status}`);
      return response.data;
    } catch (error) {
      this.logger.error(`Failed to get Tabby payment status for ${paymentId}:`, error.response?.data || error.message);
      throw new BadRequestException('فشل الحصول على حالة الدفع');
    }
  }

  /**
   * Check customer eligibility via pre-scoring
   * PRODUCTION-READY: Background check before showing Tabby option
   */
  async checkEligibility(amount: number, currency: string = 'SAR'): Promise<{ eligible: boolean; reason?: string }> {
    try {
      // Create temporary session to check eligibility
      const response = await axios.post(
        `${this.apiUrl}/checkout`,
        {
          payment: {
            amount: amount.toFixed(2),
            currency,
          },
          buyer: {
            email: 'check@example.com',
            phone: '+966500000000',
            name: 'Eligibility Check',
          },
          order: {
            reference_id: 'eligibility-' + Date.now(),
            items: [{
              title: 'Eligibility Check',
              quantity: 1,
              unit_price: amount.toFixed(2),
              category: 'Education',
            }],
          },
          merchant_urls: {
            success: process.env.FRONTEND_URL || 'http://localhost:3000',
            cancel: process.env.FRONTEND_URL || 'http://localhost:3000',
            failure: process.env.FRONTEND_URL || 'http://localhost:3000',
          },
        },
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
            'Content-Type': 'application/json',
          },
        },
      );

      const status = response.data.status;
      
      if (status === 'created') {
        return { eligible: true };
      } else if (status === 'rejected') {
        const reason = response.data.configuration?.products?.installments?.rejection_reason || 'not_available';
        return { eligible: false, reason };
      }

      return { eligible: false, reason: 'unknown' };
    } catch (error) {
      this.logger.error('Tabby eligibility check failed:', error.response?.data || error.message);
      // Default to eligible if check fails (fail open)
      return { eligible: true };
    }
  }

  /**
   * Get rejection message in Arabic
   */
  private getRejectionMessage(reason: string): string {
    const messages: Record<string, string> = {
      'not_available': 'خدمة Tabby غير متاحة حالياً',
      'order_amount_too_high': 'المبلغ أعلى من الحد المسموح به',
      'order_amount_too_low': 'المبلغ أقل من الحد الأدنى المطلوب',
    };
    return messages[reason] || 'خدمة Tabby غير متاحة لهذا الطلب';
  }

  /**
   * Capture payment (confirm the order)
   */
  async capturePayment(sessionId: string, amount: number): Promise<any> {
    try {
      const response = await axios.post(
        `${this.apiUrl}/payments/${sessionId}/captures`,
        {
          amount: amount.toFixed(2),
        },
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
            'Content-Type': 'application/json',
          },
        },
      );

      this.logger.log(`Tabby payment captured: ${sessionId}`);
      return response.data;
    } catch (error) {
      this.logger.error('Tabby payment capture failed:', error);
      throw new BadRequestException('فشل تأكيد الدفع');
    }
  }

  /**
   * Refund a Tabby payment
   */
  async refundPayment(request: BNPLRefundRequest): Promise<BNPLRefundResponse> {
    try {
      const response = await axios.post(
        `${this.apiUrl}/payments/${request.sessionId}/refunds`,
        {
          amount: request.amount.toFixed(2),
          reason: request.reason || 'Customer request',
        },
        {
          headers: {
            'Authorization': `Bearer ${this.secretKey}`,
            'Content-Type': 'application/json',
          },
        },
      );

      this.logger.log(`Tabby refund created: ${response.data.id}`);

      return {
        success: true,
        refundId: response.data.id,
      };
    } catch (error) {
      this.logger.error('Tabby refund failed:', error);
      return {
        success: false,
        error: error.response?.data?.message || 'فشل إرجاع المبلغ',
      };
    }
  }

  /**
   * Verify webhook signature
   */
  verifyWebhookSignature(payload: any, signature: string): boolean {
    // Implement Tabby webhook signature verification
    // This is a placeholder - implement according to Tabby's documentation
    return true;
  }
}
